version: '3'

services:
  tandeform:
    build: .
    image: tandeform
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
      # - redis
    env_file:
      - .env
    ports: 
      - "9000:9000"

  db:
    image: postgres:16-bullseye
    ports:
      - "5432:5432"
    restart: always
    volumes:
     - db-data:/var/lib/postgresql/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    

  # redis:
  #   image: bitnami/redis:7.2
  #   platform: linux/amd64
  #   restart: always
  #   volumes:
  #     - redis-data:/bitnami/redis/data
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    image: nginx:1.25
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/html/
    volumes_from:
      - tandeform
    depends_on:
      - tandeform
    links:
      - tandeform


volumes:
  db-data:
  # redis-data:

